### PR TITLE
[SDK] Add bot-ai-qna library

### LINKED ISSUE #740: bot-ai-qna package
QnAMaker

Depends on #743 for QnAMakerDialog

### PR DESCRIPTION
**Pull request by Batta32**
Fixes #740

- [X] Migration of source code
- [X] Migration of tests
- [X] Testing

## Description
We are adding the SDK bot-ai-qna library in Java having into account the [C# Microsoft.Bot.Builder.AI.QnA](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.AI.QnA) present in [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet) repository.

## Specific Changes
  - Generate main structure of the library
  - Migrate `dialogs` folder
  - Migrate `models` folder
  - Add `icon.png` in resources folder
  - Migrate `utils` folder
  - Migrate root files
  - Add `testData` folder
  - Add `QnAMakerRecognizerTests` unit tests
  - Add `QnAMakerTests` unit tests
  - Add `QnAMakerTraceInfoTests` unit tests

_Migrated structure_
image

_Migrated test structure_
image

## Testing
_QnA tests passing correctly 48/48_
image

_mvn clean install passing correctly_
image

## Feature Plan
\-

### CODE REVIEW

**Comment by tracyboehrer** [comment]
Parts of the QnAMakerDialog have been updated to be Adaptive friendly.  This won't apply for this version on the Java SDK since Adaptive won't be part of the GA release.

For example, in QnAMakerDialog:  StringExpression, IntegerExpression, etc...

Other:
1) QnAMakerComponentRegistration is not needed (can't actually be ported, so delete the file)
2) schemas folder can be deleted.

**Comment by Batta32** [comment]
Thanks @tracyboehrer for the feedback! We will be applying the changes as soon as we can 😊.

**Comment by Batta32** [comment]
Hi @tracyboehrer , we finished with the migration of the `bot-ai-qna` library having all the unit tests passing correctly so this is ready to be reviewed and merged 😊.

**Review by tracyboehrer — CHANGES_REQUESTED** [review]
- Drop "I" for IQnAMakerClient and ITelemetryQnAMaker to be consistent with other Java SDK interfaces
- Drop QnAMaker.kind and associated getter.  This is an Adaptive thing that isn't used yet.
- I believe we can drop QnAMaker constructor "sourceFilePath" and "sourceLineNumber".  This is part of DotNets debugging that we don't currently have in Java.
- I believe we can delete resources/icon.png.  I think this is just for NuGet packaging in DotNet.
- Is QnAMaker.httpClient (and accessors) used?  DotNet support passing in a custom client that we haven't supported anywhere else.

### Bug
QnAMaker.getAnswerRaw

```
if (messageActivity == null || messageActivity.getType() != ActivityTypes.MESSAGE) {
```

Activity.getType is a string so that comparison won't work.  Use:

```
Activity.isType(ActivityTypes.MESSAGE)
```

Recommend searching for "getType()" and see if that happens elsewhere.

### Bug

QnAMakerDialog.callTrain, line 934

```
QueryResult qnaResult = trainResponses
                .stream().filter(kvp -> kvp.getQuestions()[0] == reply).findFirst().orElse(null);
```

Performing string comparison with ==.  We typically use StringUtils.equals.

Recommend maybe searching for "==", "!=", etc... and checking for other string comparisons.  This would also help you find the previous bug.


### Minor:
QnAMaker.fillQnAEvent:

```
return CompletableFuture.completedFuture(new Pair(telemetryPropertiesResult, telemetryMetricsResult));
```

Produces an unchecked assignment warning.  Should be:

```
return CompletableFuture.completedFuture(new Pair<>(telemetryPropertiesResult, telemetryMetricsResult));
```

**Comment by tracyboehrer** [comment]
@Batta32 Lee said there is a CheckStyle rule you can add that will flag string comparisons.  That might be the quickest way to find those.  Check with him on that.  We were going to add it as part of the work Lee is doing, but its just as well if you do.

**Comment by LeeParrishMSFT** [comment]
> @Batta32 Lee said there is a CheckStyle rule you can add that will flag string comparisons. That might be the quickest way to find those. Check with him on that. We were going to add it as part of the work Lee is doing, but its just as well if you do.

This is what you can add as a child to the <module name="TreeWalker"> section:

        ****
        **<module name="StringLiteralEquality"/>**

**Comment by Batta32** [comment]
Thanks @tracyboehrer and @LeeParrishMSFT for your feedback! We will be implementing the requested changes in order to update the PR.

- `httpClient` is only used in `HttpRequestUtils` in [C#](https://github.com/microsoft/botbuilder-dotnet/blob/426b0c306dc25826a5e4837a083e9830213c60eb/libraries/Microsoft.Bot.Builder.AI.QnA/Utils/HttpRequestUtils.cs#L65) and [Java](https://github.com/southworks/botbuilder-java/blob/feature/southworks/library/bot-ai-qna/base/libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java#L56) as well. We created the client where it's used instead of adding unused properties in `QnAMaker`, `TrainUtils` and `GenerateAnswerUtils`. We can adding the property on these classes too if you want 😊.
- We will add the `StringLiteralEquality` rule in the [bot-checkstyle.xml](https://github.com/microsoft/botbuilder-java/blob/main/etc/bot-checkstyle.xml) file and fix the issues that will appear in the entire repository.

**Comment by Batta32** [comment]
Hi @tracyboehrer & @LeeParrishMSFT, we already applied the requested changes 😊.

**Review by tracyboehrer — APPROVED** [review]

**Comment by tracyboehrer** [comment]
@Batta32 Awesome!  Can you merge the latest from main?

**Comment by Batta32** [comment]
Done!

**Pull request merged**
