### PR TITLE
[SDK][Bot-Azure] Add CosmosDbPartitionedStorage component

### LINKED ISSUE #739: bot-azure, CosmosDBPartitionedStorage
Port CosmosDBPartitionedStorage from dotnet

### PR DESCRIPTION
**Pull request by VictorGrycuk**
Fixes #739

## Description

Implements support for `CosmosDbPartitionedStorage` class and its tests.

## Specific Changes

Adds the following classes:
  - `CosmosDbPartitionedStorage`
  - `CosmosDbPartitionedStorageOptions`
  - `CosmosDbKeyEscape`
  - Updates the `pom.xml` file with the necessary dependencies
  - Adds the necessary tests for the `CosmosDbPartitionedStorage` and `CosmosDbKeyEscape` classes

## Testing

_Unit tests of bot-azure passing correctly_
image

_mvn clean install passing correctly_
image

### CODE REVIEW

**Comment by VictorGrycuk** [comment]
@tracyboehrer we noticed that the **build is failing**, most likely due to the bot-azure tests.

Those unit tests contain the following **requirements** to be executed:
1. `CosmosDbEmulator application`:
    1. On BotBuilder-DotNet we found a commented configuration for [starting CosmosDBEmulator](https://github.com/microsoft/botbuilder-dotnet/blob/4dc5f99ec0d45d78d53c7d11cc3f7c8d86578991/build/yaml/ci-test-steps.yml#L10-L16) that was added in microsoft/botbuilder-dotnet#3115. Then disabled in PR microsoft/botbuilder-dotnet#3815 because of unreliability due to time-outs. Finally re-enabled in microsoft/botbuilder-dotnet#3816 to find a solution.
     2. On BotBuilder-JS we found a [cmd file](https://github.com/microsoft/botbuilder-js/blob/1abcd397729565e28e6250edb9aa85fbf919b094/prep-test.cmd) that initializes the CosmosDbEmulator as a preparation of the tests, as indicates [this document](https://github.com/microsoft/botbuilder-js/blob/131eebf9a0d5e7cc2a51481211fcfa7c8544e46a/README.md#running-unit-tests).
3. `CosmosDbEmulator certificates`: after starting the emulator and running the unit tests for CosmosDbPartitionedStorage we go the following message:
> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This is because Java needs the CosmosDbEmulator certificate in its `cacert`. We solved this by following [this guide](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator-export-ssl-certificates), which basically involves exporting the CosmosDbEmulator certificate, and importing it to the Java `cacert` repository.

We don't have permissions to analyze the build pipeline, however, let us know if you need help from our side for this 😊.

**Comment by VictorGrycuk** [comment]
@tracyboehrer we **removed** the following files as they are generated during the build:
- `DocumentDB.Spatial.Sql.dll`
- `Microsoft.Azure.Documents.ServiceInterop.dll`

We noticed that the [.gitignore](https://github.com/microsoft/botbuilder-java/blob/trboehre/cosmosdbpartionedstorage/.gitignore) is missing a configuration for these files. Do you want us to add an entry in the configuration to ignore these binaries?

**Comment by tracyboehrer** [comment]
@VictorGrycuk So these unit tests require the cosmosdb emulator and that appears to be why the PR builder is failing.  I need to look into how DotNet is dealing with this.

**Comment by tracyboehrer** [comment]
@VictorGrycuk For the time being, I disabled running one of the unit tests for this in DevOps.  This isn't a permanent solution, but we'll have to do some more research on our side.  If you have the emulator installed, it will still run the unit tests as before.  For DevOps, or if you try to run mvn and you DON'T have the emulator installed, you must include the following mvn options:

```
-Dtest=!CosmosDbPartitionStorageTests* -DfailIfNoTests=false
```

Not sure I really like this solution, but it does have the advantage of annoying me enough to provide motivation to solve the problem for real.

**Pull request merged**
