### PR TITLE
Add linkToMessage property to MessageActionsPayload class

### LINKED ISSUE #622: Add linkToMessage to the MessageActionsPayload object (Java)
See [parent](https://github.com/microsoft/botframework-sdk/issues/5894)

### PR DESCRIPTION
**Pull request by denscollo**
Fixes #622
## Description
This pull request adds the `linkToMessage` property to the `MessageActionsPayload` class from BotBuilder-Schema library. By adding this property, it can add the link provided in the payload from MS-Teams.
Also, we added tests for the methods of the class.

## Specific Changes
- Added the `linkToMessage` property to the `MessageActionsPayload` class from BotBuilder-Schema
- Created the `MessageActionsPayloadTest.java` file inside the `test/teams` folder of the library.
- Added tests for all the methods of the `MessageActionsPayload` in that test class.

 ## Testing
In the following image, you can see the bot assigns the `linkToMessage` property when sharing a card in MS-Teams, using the `51.teams-messaging-extensions-action` sample from the same repository.
image

And in the next image, you can see the added tests passing.
image

### CODE REVIEW

**Comment by tracyboehrer** [comment]
@JuanAr @santgr11 While not at all obvious, this PR is failing the build check due to some CheckStyle errors in Schema.  If you perform a "mvn package" from the Java SDK root, it should generate a checkstyle-result.xml or pmd.xml in the libraries/botbuilder-schema/target folder.

**Comment by denscollo** [comment]
Thanks @tracyboehrer, we were reviewing the logs to find what the issue was. We'll work on this to have the PR ready. Thanks

**Comment by tracyboehrer** [comment]
@denscollo Thanks!  This issue is on my list of things to correct.  It throws everyone.  I believe there is a way to make those errors more obvious without having to dig into the DevOps logs.

**Comment by denscollo** [comment]
@tracyboehrer We just pushed the styling fix and the build succedeed! Thanks 😄

**Pull request merged**
